name: ${name}
version: ${version}
main: io.github.mcpaimon.papermc.MCAgentsPlugin
api-version: '1.20'
author: MCPaimon
description: A plugin for PaperMC

commands:
  mcaiextension:
    description: Manage MCExtension plugins
    usage: /mcaiextension <load|unload|reload|list>
    permission: mcaiextension.admin

permissions:
  mcaiextension.admin:
    description: Allows management of MCExtension plugins
    default: op

libraries:
  - com.zaxxer:HikariCP:7.0.2
  - org.mongodb:mongodb-driver-sync:5.7.0
